spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forum?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    port: 587
    username: 2464859727@qq.com
    password: oujvjsnnpkamdiie
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

app:
  upload:
    dir: D:/forum/backend/uploads/

qweather:
  host: https://nk6mthkn5k.re.qweatherapi.com
  kid: KEB55MARN2
  sub: 2AE3U8NW7V
  iss: Q1722007A5
  private-key-path: D:/forum/backend/ed25519-private.pem
mybatis-plus:
  global-config:
    db-config:
      id-type: auto