spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forum?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
qweather:
  host: https://nk6mthkn5k.re.qweatherapi.com
  kid: KEB55MARN2
  sub: 2AE3U8NW7V
  iss: Q1722007A5
  private-key-path: D:/forum/backend/ed25519-private.pem